
name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build
        id: build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        id: docker_login
        if: steps.build.outcome == 'success'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        id: docker_build
        if: steps.docker_login.outcome == 'success'
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/expense-react-app:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        if: steps.docker_build.outcome == 'success'
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.DOCKER_USERNAME }}/expense-react-app:latest

    #   - name: Generate deployment package
    #     run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to AWS Elastic Beanstalk
      #   if: steps.build.outcome == 'success'
      #   uses: einaregilsson/beanstalk-deploy@v21
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     application_name: ${{ secrets.EB_APPLICATION_NAME }}
      #     environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
      #     region: ${{ secrets.AWS_REGION }}
      #     version_label: expense-react-app-${{ github.sha }}
      #     deployment_package: Dockerrun.aws.json
      #     existing_bucket_name: elasticbeanstalk-us-east-1-923445559289


    #   - name: Deploy to GitHub Pages
    #     if: steps.build.outcome == 'success'
    #     uses: peaceiris/actions-gh-pages@v3
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       publish_dir: ./build