name: "Build and Deploy to Azure (DockerHub SHA Tags)"

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_SECURE_PASSWORD: ${{ secrets.DB_SECURE_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Image Tag
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set DATABASE_URL
        run: |
          echo "DATABASE_URL=sqlserver://$DB_HOST:1433;database=$DB_NAME;user=$DB_USER;password=$DB_SECURE_PASSWORD;encrypt=true;trustServerCertificate=false" >> $GITHUB_ENV
          echo "$DATABASE_URL"

      - name: Render Compose File
        run: |
          export IMAGE_TAG=$IMAGE_TAG
          export DATABASE_URL=$DATABASE_URL
          echo "$DATABASE_URL"
          echo "$DB_SECURE_PASSWORD"
          envsubst < docker-compose.prod.yml > docker-compose.rendered.yml

      - name: Build and Push Images
        run: |
          docker compose -f docker-compose.rendered.yml build
          docker compose -f docker-compose.rendered.yml push

      - name: Deploy to Azure
        run: |
          az webapp config container set \
            --name $AZURE_WEBAPP_NAME \
            --resource-group $AZURE_RESOURCE_GROUP \
            --docker-registry-server-url https://index.docker.io/v1/ \
            --docker-registry-server-user $DOCKER_USERNAME \
            --docker-registry-server-password $DOCKER_PASSWORD \
            --multicontainer-config-type compose \
            --multicontainer-config-file docker-compose.rendered.yml

          az webapp restart \
            --name $AZURE_WEBAPP_NAME \
            --resource-group $AZURE_RESOURCE_GROUP
